#!/usr/bin/env python3
"""
Action Item Tracker - Setup Script
This script helps with the initial setup and configuration of the application.
"""

import os
import sys
import subprocess
import secrets
import getpass
from pathlib import Path

def print_header():
    """Print the setup header."""
    print("=" * 60)
    print("🚀 Action Item Tracker - Setup Wizard")
    print("=" * 60)
    print("This wizard will help you set up your Action Item Tracker application.")
    print()

def check_python_version():
    """Check Python version."""
    if sys.version_info < (3, 8):
        print("❌ Error: Python 3.8 or higher is required.")
        print(f"Current version: {sys.version}")
        sys.exit(1)
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro} detected")

def setup_virtual_environment():
    """Set up virtual environment."""
    if os.path.exists('venv'):
        print("✅ Virtual environment already exists")
        return True
    
    print("📦 Creating virtual environment...")
    try:
        subprocess.run([sys.executable, '-m', 'venv', 'venv'], check=True)
        print("✅ Virtual environment created successfully")
        
        # Determine activation script path
        if os.name == 'nt':  # Windows
            activate_script = 'venv\\Scripts\\activate'
        else:  # Unix/Linux/macOS
            activate_script = 'source venv/bin/activate'
        
        print(f"💡 To activate the virtual environment, run: {activate_script}")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to create virtual environment")
        return False

def install_dependencies():
    """Install Python dependencies."""
    print("📦 Installing dependencies...")
    
    # Determine pip path
    if os.name == 'nt':  # Windows
        pip_path = os.path.join('venv', 'Scripts', 'pip')
    else:  # Unix/Linux/macOS
        pip_path = os.path.join('venv', 'bin', 'pip')
    
    if not os.path.exists(pip_path):
        pip_path = 'pip'  # Fallback to system pip
    
    try:
        subprocess.run([pip_path, 'install', '-r', 'requirements.txt'], check=True)
        print("✅ Dependencies installed successfully")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to install dependencies")
        print("💡 Try running: pip install -r requirements.txt")
        return False

def collect_database_info():
    """Collect database configuration from user."""
    print("\n🗄️  Database Configuration")
    print("-" * 30)
    
    db_config = {}
    
    # Database server
    default_server = "localhost"
    db_config['server'] = input(f"Database server [{default_server}]: ").strip() or default_server
    
    # Database name
    default_name = "ActionItemDB"
    db_config['name'] = input(f"Database name [{default_name}]: ").strip() or default_name
    
    # Username
    default_username = "sa"
    db_config['username'] = input(f"Database username [{default_username}]: ").strip() or default_username
    
    # Password
    while True:
        password = getpass.getpass("Database password: ")
        if password:
            db_config['password'] = password
            break
        print("Password cannot be empty. Please try again.")
    
    return db_config

def create_env_file(db_config):
    """Create .env file with configuration."""
    print("\n⚙️  Creating configuration file...")
    
    # Generate a secure secret key
    secret_key = secrets.token_urlsafe(32)
    
    env_content = f"""# Action Item Tracker Configuration
# Generated by setup script

# Application Settings
SECRET_KEY={secret_key}

# Database Configuration
DB_SERVER={db_config['server']}
DB_NAME={db_config['name']}
DB_USERNAME={db_config['username']}
DB_PASSWORD={db_config['password']}

# Application Environment
FLASK_ENV=development
FLASK_DEBUG=True

# Optional: Email Configuration (for future notifications)
# MAIL_SERVER=smtp.gmail.com
# MAIL_PORT=587
# MAIL_USE_TLS=True
# MAIL_USERNAME=your_email@gmail.com
# MAIL_PASSWORD=your_app_password
# MAIL_DEFAULT_SENDER=your_email@gmail.com
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ Configuration file (.env) created successfully")

def test_database_connection(db_config):
    """Test database connection."""
    print("\n🔍 Testing database connection...")
    
    try:
        import pyodbc
        
        driver = 'ODBC Driver 17 for SQL Server'
        conn_string = (
            f"DRIVER={{{driver}}};"
            f"SERVER={db_config['server']};"
            f"DATABASE={db_config['name']};"
            f"UID={db_config['username']};"
            f"PWD={db_config['password']}"
        )
        
        conn = pyodbc.connect(conn_string, timeout=10)
        conn.close()
        print("✅ Database connection successful!")
        return True
        
    except ImportError:
        print("⚠️  pyodbc not available, skipping connection test")
        return True
    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        print("\n💡 Common solutions:")
        print("   1. Ensure SQL Server is running")
        print("   2. Check database server name and credentials")
        print("   3. Verify ODBC Driver 17 for SQL Server is installed")
        print("   4. Check firewall and network connectivity")
        return False

def create_database_if_needed(db_config):
    """Offer to create database if it doesn't exist."""
    print(f"\n🗄️  Checking if database '{db_config['name']}' exists...")
    
    try:
        import pyodbc
        
        # Connect to master database to check if target database exists
        driver = 'ODBC Driver 17 for SQL Server'
        conn_string = (
            f"DRIVER={{{driver}}};"
            f"SERVER={db_config['server']};"
            f"DATABASE=master;"
            f"UID={db_config['username']};"
            f"PWD={db_config['password']}"
        )
        
        conn = pyodbc.connect(conn_string, timeout=10)
        cursor = conn.cursor()
        
        # Check if database exists
        cursor.execute(
            "SELECT name FROM sys.databases WHERE name = ?", 
            db_config['name']
        )
        
        if cursor.fetchone():
            print(f"✅ Database '{db_config['name']}' already exists")
        else:
            print(f"⚠️  Database '{db_config['name']}' does not exist")
            create_db = input("Would you like to create it? (y/N): ").lower()
            
            if create_db in ['y', 'yes']:
                cursor.execute(f"CREATE DATABASE [{db_config['name']}]")
                conn.commit()
                print(f"✅ Database '{db_config['name']}' created successfully")
            else:
                print("💡 You'll need to create the database manually before running the application")
        
        cursor.close()
        conn.close()
        return True
        
    except ImportError:
        print("⚠️  pyodbc not available, skipping database creation")
        return True
    except Exception as e:
        print(f"❌ Database check failed: {e}")
        return False

def display_next_steps():
    """Display next steps for the user."""
    print("\n🎉 Setup completed successfully!")
    print("=" * 60)
    print("\n📋 Next Steps:")
    print("1. Activate your virtual environment:")
    
    if os.name == 'nt':  # Windows
        print("   venv\\Scripts\\activate")
    else:  # Unix/Linux/macOS
        print("   source venv/bin/activate")
    
    print("\n2. Run the database schema script:")
    print("   sqlcmd -S your_server -d ActionItemDB -i database_schema.sql")
    print("   (or execute database_schema.sql in SQL Server Management Studio)")
    
    print("\n3. Start the application:")
    print("   python run.py")
    print("   (or python app.py)")
    
    print("\n4. Open your browser and navigate to:")
    print("   http://localhost:5000")
    
    print("\n5. Register your first user account and start creating action items!")
    
    print("\n📖 For more information, see README.md")
    print("🐛 For issues, check the troubleshooting section in README.md")

def main():
    """Main setup function."""
    print_header()
    
    # Check Python version
    check_python_version()
    
    # Set up virtual environment
    if not setup_virtual_environment():
        sys.exit(1)
    
    # Install dependencies
    if not install_dependencies():
        print("⚠️  Continue setup anyway? Dependencies can be installed manually later.")
        if input("Continue? (y/N): ").lower() not in ['y', 'yes']:
            sys.exit(1)
    
    # Skip if .env already exists
    if os.path.exists('.env'):
        print("\n✅ Configuration file (.env) already exists")
        overwrite = input("Would you like to overwrite it? (y/N): ").lower()
        if overwrite not in ['y', 'yes']:
            print("Keeping existing configuration...")
            display_next_steps()
            return
    
    # Collect database configuration
    db_config = collect_database_info()
    
    # Create .env file
    create_env_file(db_config)
    
    # Test database connection
    if not test_database_connection(db_config):
        print("\n⚠️  Database connection failed, but setup will continue.")
        print("Please verify your database configuration in the .env file.")
    
    # Offer to create database
    create_database_if_needed(db_config)
    
    # Display next steps
    display_next_steps()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed with error: {e}")
        print("Please check the error message and try again.")
        sys.exit(1)